/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as AuthenticatedMyWithdrawalsRouteImport } from './routes/_authenticated/my-withdrawals'
import { Route as AuthenticatedMyDepositsRouteImport } from './routes/_authenticated/my-deposits'
import { Route as AuthenticatedDepositRouteImport } from './routes/_authenticated/deposit'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAgencyWithdrawalsRouteImport } from './routes/_authenticated/agency/withdrawals'
import { Route as AuthenticatedAgencyDividendosRouteImport } from './routes/_authenticated/agency/dividendos'
import { Route as AuthenticatedAgencyDepositsRouteImport } from './routes/_authenticated/agency/deposits'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminHipodromosRouteImport } from './routes/_authenticated/admin/hipodromos'
import { Route as AuthenticatedAdminAgenciesRouteImport } from './routes/_authenticated/admin/agencies'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyWithdrawalsRoute =
  AuthenticatedMyWithdrawalsRouteImport.update({
    id: '/my-withdrawals',
    path: '/my-withdrawals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyDepositsRoute = AuthenticatedMyDepositsRouteImport.update({
  id: '/my-deposits',
  path: '/my-deposits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepositRoute = AuthenticatedDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgencyWithdrawalsRoute =
  AuthenticatedAgencyWithdrawalsRouteImport.update({
    id: '/agency/withdrawals',
    path: '/agency/withdrawals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgencyDividendosRoute =
  AuthenticatedAgencyDividendosRouteImport.update({
    id: '/agency/dividendos',
    path: '/agency/dividendos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgencyDepositsRoute =
  AuthenticatedAgencyDepositsRouteImport.update({
    id: '/agency/deposits',
    path: '/agency/deposits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminHipodromosRoute =
  AuthenticatedAdminHipodromosRouteImport.update({
    id: '/admin/hipodromos',
    path: '/admin/hipodromos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAgenciesRoute =
  AuthenticatedAdminAgenciesRouteImport.update({
    id: '/admin/agencies',
    path: '/admin/agencies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deposit': typeof AuthenticatedDepositRoute
  '/my-deposits': typeof AuthenticatedMyDepositsRoute
  '/my-withdrawals': typeof AuthenticatedMyWithdrawalsRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/agencies': typeof AuthenticatedAdminAgenciesRoute
  '/admin/hipodromos': typeof AuthenticatedAdminHipodromosRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/agency/deposits': typeof AuthenticatedAgencyDepositsRoute
  '/agency/dividendos': typeof AuthenticatedAgencyDividendosRoute
  '/agency/withdrawals': typeof AuthenticatedAgencyWithdrawalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deposit': typeof AuthenticatedDepositRoute
  '/my-deposits': typeof AuthenticatedMyDepositsRoute
  '/my-withdrawals': typeof AuthenticatedMyWithdrawalsRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/agencies': typeof AuthenticatedAdminAgenciesRoute
  '/admin/hipodromos': typeof AuthenticatedAdminHipodromosRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/agency/deposits': typeof AuthenticatedAgencyDepositsRoute
  '/agency/dividendos': typeof AuthenticatedAgencyDividendosRoute
  '/agency/withdrawals': typeof AuthenticatedAgencyWithdrawalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deposit': typeof AuthenticatedDepositRoute
  '/_authenticated/my-deposits': typeof AuthenticatedMyDepositsRoute
  '/_authenticated/my-withdrawals': typeof AuthenticatedMyWithdrawalsRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
  '/_authenticated/admin/agencies': typeof AuthenticatedAdminAgenciesRoute
  '/_authenticated/admin/hipodromos': typeof AuthenticatedAdminHipodromosRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/agency/deposits': typeof AuthenticatedAgencyDepositsRoute
  '/_authenticated/agency/dividendos': typeof AuthenticatedAgencyDividendosRoute
  '/_authenticated/agency/withdrawals': typeof AuthenticatedAgencyWithdrawalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/deposit'
    | '/my-deposits'
    | '/my-withdrawals'
    | '/withdraw'
    | '/admin/agencies'
    | '/admin/hipodromos'
    | '/admin/users'
    | '/agency/deposits'
    | '/agency/dividendos'
    | '/agency/withdrawals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/deposit'
    | '/my-deposits'
    | '/my-withdrawals'
    | '/withdraw'
    | '/admin/agencies'
    | '/admin/hipodromos'
    | '/admin/users'
    | '/agency/deposits'
    | '/agency/dividendos'
    | '/agency/withdrawals'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/deposit'
    | '/_authenticated/my-deposits'
    | '/_authenticated/my-withdrawals'
    | '/_authenticated/withdraw'
    | '/_authenticated/admin/agencies'
    | '/_authenticated/admin/hipodromos'
    | '/_authenticated/admin/users'
    | '/_authenticated/agency/deposits'
    | '/_authenticated/agency/dividendos'
    | '/_authenticated/agency/withdrawals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-withdrawals': {
      id: '/_authenticated/my-withdrawals'
      path: '/my-withdrawals'
      fullPath: '/my-withdrawals'
      preLoaderRoute: typeof AuthenticatedMyWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-deposits': {
      id: '/_authenticated/my-deposits'
      path: '/my-deposits'
      fullPath: '/my-deposits'
      preLoaderRoute: typeof AuthenticatedMyDepositsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deposit': {
      id: '/_authenticated/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof AuthenticatedDepositRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agency/withdrawals': {
      id: '/_authenticated/agency/withdrawals'
      path: '/agency/withdrawals'
      fullPath: '/agency/withdrawals'
      preLoaderRoute: typeof AuthenticatedAgencyWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agency/dividendos': {
      id: '/_authenticated/agency/dividendos'
      path: '/agency/dividendos'
      fullPath: '/agency/dividendos'
      preLoaderRoute: typeof AuthenticatedAgencyDividendosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agency/deposits': {
      id: '/_authenticated/agency/deposits'
      path: '/agency/deposits'
      fullPath: '/agency/deposits'
      preLoaderRoute: typeof AuthenticatedAgencyDepositsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/hipodromos': {
      id: '/_authenticated/admin/hipodromos'
      path: '/admin/hipodromos'
      fullPath: '/admin/hipodromos'
      preLoaderRoute: typeof AuthenticatedAdminHipodromosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/agencies': {
      id: '/_authenticated/admin/agencies'
      path: '/admin/agencies'
      fullPath: '/admin/agencies'
      preLoaderRoute: typeof AuthenticatedAdminAgenciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepositRoute: typeof AuthenticatedDepositRoute
  AuthenticatedMyDepositsRoute: typeof AuthenticatedMyDepositsRoute
  AuthenticatedMyWithdrawalsRoute: typeof AuthenticatedMyWithdrawalsRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
  AuthenticatedAdminAgenciesRoute: typeof AuthenticatedAdminAgenciesRoute
  AuthenticatedAdminHipodromosRoute: typeof AuthenticatedAdminHipodromosRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAgencyDepositsRoute: typeof AuthenticatedAgencyDepositsRoute
  AuthenticatedAgencyDividendosRoute: typeof AuthenticatedAgencyDividendosRoute
  AuthenticatedAgencyWithdrawalsRoute: typeof AuthenticatedAgencyWithdrawalsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepositRoute: AuthenticatedDepositRoute,
  AuthenticatedMyDepositsRoute: AuthenticatedMyDepositsRoute,
  AuthenticatedMyWithdrawalsRoute: AuthenticatedMyWithdrawalsRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
  AuthenticatedAdminAgenciesRoute: AuthenticatedAdminAgenciesRoute,
  AuthenticatedAdminHipodromosRoute: AuthenticatedAdminHipodromosRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAgencyDepositsRoute: AuthenticatedAgencyDepositsRoute,
  AuthenticatedAgencyDividendosRoute: AuthenticatedAgencyDividendosRoute,
  AuthenticatedAgencyWithdrawalsRoute: AuthenticatedAgencyWithdrawalsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
