
CREATE TABLE public.dividendos (
  id_div bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idhip varchar(6) NOT NULL REFERENCES public.hipodromos(idhip) ON DELETE CASCADE,
  idage integer NOT NULL REFERENCES public.agencies(id) ON DELETE CASCADE,
  desde numeric(14,2) NOT NULL DEFAULT 0,
  hasta numeric(14,2) NOT NULL DEFAULT 0,
  fijo numeric(14,2) NOT NULL DEFAULT 0,
  adicional numeric(14,2) NOT NULL DEFAULT 0,
  fijod numeric(14,2) NOT NULL DEFAULT 0,
  adicionald numeric(14,2) NOT NULL DEFAULT 0,
  divfijo numeric(14,2) NOT NULL DEFAULT 0,
  desdep numeric(14,2) NOT NULL DEFAULT 0,
  hastap numeric(14,2) NOT NULL DEFAULT 0,
  fijop numeric(14,2) NOT NULL DEFAULT 0,
  adicionalp numeric(14,2) NOT NULL DEFAULT 0,
  divfijop numeric(14,2) NOT NULL DEFAULT 0,
  desdes numeric(14,2) NOT NULL DEFAULT 0,
  hastas numeric(14,2) NOT NULL DEFAULT 0,
  fijos numeric(14,2) NOT NULL DEFAULT 0,
  adicionals numeric(14,2) NOT NULL DEFAULT 0,
  divfijos numeric(14,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX dividendos_hip_age_idx ON public.dividendos(idhip, idage);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.dividendos TO authenticated;
GRANT ALL ON public.dividendos TO service_role;

ALTER TABLE public.dividendos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "dividendos_admin_all" ON public.dividendos
  TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::app_role))
  WITH CHECK (public.has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "dividendos_agency_select" ON public.dividendos
  FOR SELECT TO authenticated
  USING (
    public.has_role(auth.uid(), 'agency'::app_role)
    AND idage = (SELECT agency_id FROM public.profiles WHERE id = auth.uid())
  );

CREATE POLICY "dividendos_agency_insert" ON public.dividendos
  FOR INSERT TO authenticated
  WITH CHECK (
    public.has_role(auth.uid(), 'agency'::app_role)
    AND idage = (SELECT agency_id FROM public.profiles WHERE id = auth.uid())
  );

CREATE POLICY "dividendos_agency_update" ON public.dividendos
  FOR UPDATE TO authenticated
  USING (
    public.has_role(auth.uid(), 'agency'::app_role)
    AND idage = (SELECT agency_id FROM public.profiles WHERE id = auth.uid())
  )
  WITH CHECK (
    public.has_role(auth.uid(), 'agency'::app_role)
    AND idage = (SELECT agency_id FROM public.profiles WHERE id = auth.uid())
  );

CREATE POLICY "dividendos_agency_delete" ON public.dividendos
  FOR DELETE TO authenticated
  USING (
    public.has_role(auth.uid(), 'agency'::app_role)
    AND idage = (SELECT agency_id FROM public.profiles WHERE id = auth.uid())
  );

CREATE TRIGGER dividendos_set_updated_at
  BEFORE UPDATE ON public.dividendos
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
